import type { Database } from "@/lib/supabase/types";

type Inquiry = Database["public"]["Tables"]["inquiries"]["Row"];
type Contact = Database["public"]["Tables"]["contacts"]["Row"];
type Deal = Database["public"]["Tables"]["deals"]["Row"];
type Booking = Database["public"]["Tables"]["bookings"]["Row"];

const now = new Date();
const iso = (daysFromNow: number, hour = 10) => {
  const date = new Date(now);
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

export const demoInquiries: Inquiry[] = [
  {
    id: "demo-inquiry-1",
    created_at: iso(-1, 14),
    status: "new",
    business_type: "Local service business",
    goal: "More booked jobs & leads",
    name: "Jake Miller",
    business: "Summit Roofing Co.",
    handle: "@summitroofing",
    email: "jake@summitroofing.co",
    phone: "(512) 555-0128",
    message: "Need a steady content system for roofing jobs and before/after reels.",
    source: "get-started",
    raw_payload: {},
  },
  {
    id: "demo-inquiry-2",
    created_at: iso(-3, 11),
    status: "reviewed",
    business_type: "Restaurant & hospitality",
    goal: "Consistent content",
    name: "Maya Torres",
    business: "North Loop Social",
    handle: "northloopsocial.com",
    email: "maya@northloopsocial.com",
    phone: null,
    message: "Opening a new patio and want launch content plus weekly clips.",
    source: "get-started",
    raw_payload: {},
  },
];

export const demoContacts: Contact[] = [
  {
    id: "demo-contact-1",
    created_at: iso(-10),
    updated_at: iso(-2),
    inquiry_id: "demo-inquiry-1",
    name: "Jake Miller",
    business: "Summit Roofing Co.",
    email: "jake@summitroofing.co",
    phone: "(512) 555-0128",
    handle: "@summitroofing",
    business_type: "Local service business",
    notes: "Strong fit for managed content. Wants job-site volume.",
  },
  {
    id: "demo-contact-2",
    created_at: iso(-16),
    updated_at: iso(-1),
    inquiry_id: null,
    name: "Chris Vaughn",
    business: "Vaughn Custom Homes",
    email: "chris@vaughnhomes.com",
    phone: "(479) 555-0184",
    handle: "@vaughnhomes",
    business_type: "Custom builder",
    notes: "Needs founder-led trust content and project walkthroughs.",
  },
];

export const demoDeals: Deal[] = [
  {
    id: "demo-deal-1",
    created_at: iso(-10),
    updated_at: iso(-1),
    contact_id: "demo-contact-1",
    inquiry_id: "demo-inquiry-1",
    title: "Summit Roofing managed content",
    status: "call_booked",
    value: 4500,
    next_follow_up: iso(1).slice(0, 10),
    notes: "Pitch: two shoot days per month, 80+ deliverables, review call weekly.",
  },
  {
    id: "demo-deal-2",
    created_at: iso(-16),
    updated_at: iso(-4),
    contact_id: "demo-contact-2",
    inquiry_id: null,
    title: "Vaughn Homes white-glove",
    status: "proposal_sent",
    value: 9000,
    next_follow_up: iso(2).slice(0, 10),
    notes: "Proposal sent for full white-glove with monthly portal review.",
  },
  {
    id: "demo-deal-3",
    created_at: iso(-4),
    updated_at: iso(-2),
    contact_id: null,
    inquiry_id: "demo-inquiry-2",
    title: "North Loop Social launch",
    status: "contacted",
    value: 3200,
    next_follow_up: iso(3).slice(0, 10),
    notes: "Needs launch sprint and evergreen content after patio opening.",
  },
  {
    id: "demo-deal-4",
    created_at: iso(-8),
    updated_at: iso(-1),
    contact_id: null,
    inquiry_id: null,
    title: "Blue Ridge HVAC reels",
    status: "new_inquiry",
    value: 2800,
    next_follow_up: iso(2).slice(0, 10),
    notes: "Service-call proof content and technician-led clips.",
  },
  {
    id: "demo-deal-5",
    created_at: iso(-6),
    updated_at: iso(-2),
    contact_id: null,
    inquiry_id: null,
    title: "Oakline Builders launch",
    status: "new_inquiry",
    value: 5200,
    next_follow_up: iso(4).slice(0, 10),
    notes: "Custom home walkthroughs and founder story content.",
  },
  {
    id: "demo-deal-6",
    created_at: iso(-7),
    updated_at: iso(-3),
    contact_id: null,
    inquiry_id: null,
    title: "Ironwood Exteriors",
    status: "contacted",
    value: 4100,
    next_follow_up: iso(1).slice(0, 10),
    notes: "Before-and-after installs, weekly posting cadence.",
  },
  {
    id: "demo-deal-7",
    created_at: iso(-9),
    updated_at: iso(-2),
    contact_id: null,
    inquiry_id: null,
    title: "Hawthorne Dental social",
    status: "call_booked",
    value: 3600,
    next_follow_up: iso(5).slice(0, 10),
    notes: "Trust-building content and patient education series.",
  },
  {
    id: "demo-deal-8",
    created_at: iso(-12),
    updated_at: iso(-1),
    contact_id: null,
    inquiry_id: null,
    title: "All County Roofing",
    status: "proposal_sent",
    value: 7800,
    next_follow_up: iso(2).slice(0, 10),
    notes: "Managed package with two shoot days monthly.",
  },
  {
    id: "demo-deal-9",
    created_at: iso(-20),
    updated_at: iso(-2),
    contact_id: null,
    inquiry_id: null,
    title: "Cedar Creek Pools",
    status: "won",
    value: 6200,
    next_follow_up: null,
    notes: "Won managed content retainer.",
  },
  {
    id: "demo-deal-10",
    created_at: iso(-22),
    updated_at: iso(-5),
    contact_id: null,
    inquiry_id: null,
    title: "Riverbend Fitness",
    status: "won",
    value: 3900,
    next_follow_up: null,
    notes: "Won launch sprint and monthly clips.",
  },
  {
    id: "demo-deal-11",
    created_at: iso(-18),
    updated_at: iso(-6),
    contact_id: null,
    inquiry_id: null,
    title: "Metro Window Co.",
    status: "lost",
    value: 2500,
    next_follow_up: null,
    notes: "Paused until Q4.",
  },
];

export const demoBookings: Booking[] = [
  {
    id: "demo-booking-1",
    created_at: iso(-2),
    updated_at: iso(-2),
    deal_id: "demo-deal-1",
    contact_id: "demo-contact-1",
    title: "Summit Roofing discovery call",
    starts_at: iso(1, 13),
    ends_at: iso(1, 13),
    status: "scheduled",
    location: "Google Meet",
    notes: "Walk through current Instagram and recent jobs.",
  },
  {
    id: "demo-booking-2",
    created_at: iso(-5),
    updated_at: iso(-4),
    deal_id: "demo-deal-2",
    contact_id: "demo-contact-2",
    title: "Campaign review",
    starts_at: iso(4, 10),
    ends_at: iso(4, 11),
    status: "scheduled",
    location: "Phone",
    notes: "Review proposal and first 30 days of shoot concepts.",
  },
];
